name: $(Year:yy)$(DayOfYear).$(Rev:r)

trigger: none

pool:
  name: Default

variables:
- group: helm-test
- name: chartPackage
  value: ./finance-app-backend-0.1.0.tgz

stages:
  - stage: CD
    displayName: 'Despliegue Continuo'
    jobs:
      - job: Deploy_Minikube
        displayName: 'Deploy en Minikube con Helm'
        steps:
          - checkout: self

          - script: |
              minikube status || minikube start
            displayName: "Iniciar Minikube"

          - script: |
              kubectl create secret generic finance-app-secrets --from-literal=SPRING_DATASOURCE_USERNAME=$(DB_USER) --from-literal=SPRING_DATASOURCE_PASSWORD=$(DB_PASSWORD) --from-literal=MYSQL_ROOT_PASSWORD=$(DB_PASSWORD) --from-literal=MYSQL_DATABASE=$(DATABASE) --from-literal=MYSQL_USER=$(DB_USER) --from-literal=MYSQL_PASSWORD=$(DB_PASSWORD) --dry-run=client -o yaml | kubectl apply -f -

              kubectl create configmap finance-app-config --from-literal=SPRING_DATASOURCE_URL="jdbc:mysql://finance-app-database:3306/$(DATABASE)" --dry-run=client -o yaml | kubectl apply -f -
            displayName: "Crear ConfigMap y Secrets"

          - script: |
              aws configure set aws_access_key_id $(CLI_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(CLI_ACCESS_KEY)
              aws configure set region $(AWS_REGION)
              aws sts get-caller-identity
            displayName: 'Configurar credenciales de AWS CLI'

          - script: |
              aws s3 cp $(S3_CHART_URI) $(chartPackage)
            displayName: 'Descargar Helm Chart desde S3'

          - script: |
              aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(ECR_REPOSITORY_URL)
            displayName: 'Autenticarse en AWS ECR para Docker'

          - task: PowerShell@2
            displayName: 'Crear o actualizar imagePullSecret en Kubernetes'
            inputs:
              targetType: inline
              script: |
                $ECR_PASSWORD = aws ecr get-login-password --region $(AWS_REGION)
                kubectl create secret docker-registry ecr-secret `
                  --docker-server=$(ECR_REPOSITORY_SERVER) `
                  --docker-username=AWS `
                  --docker-password=$ECR_PASSWORD `
                  --dry-run=client -o yaml | kubectl apply -f -

          - task: PowerShell@2
            displayName: "Obtener última versión de la imagen"
            inputs:
              targetType: inline
              script: |
                $latestTag = aws ecr describe-images --repository-name 'ecr-lab-financeapp' --query 'imageDetails | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' --output text
                echo "##vso[task.setvariable variable=LATEST_TAG]$latestTag"

          - script: |
              helm upgrade --install --set image.tag=$(LATEST_TAG) finance-app $(chartPackage)
            displayName: "Actualizar release con Helm"
