name: $(Year:yy)$(DayOfYear).$(Rev:r) 

trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
- group: helm-test

stages:
  - stage: CI
    displayName: 'Integración Continua'
    jobs:
      - job: Construir_Subir_Imagen
        displayName: 'Construir y Subir Imagen Docker'
        steps:
          - checkout: self

          - script: |
              aws configure set aws_access_key_id $(CLI_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(CLI_ACCESS_KEY)
              aws configure set region $(AWS_REGION)
              aws sts get-caller-identity
            displayName: 'Verificar Credenciales de AWS'

          - script: |
              aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(ECR_REPOSITORY_URL)
            displayName: 'Iniciar sesión en AWS ECR'

          - task: PowerShell@2
            displayName: 'Inicar Docker Desktop'
            inputs:
              targetType: 'inline'
              script: |
                Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
                Start-Sleep -Seconds 20

          - task: Docker@2
            displayName: 'Construir Imagen y Subir a ECR'
            inputs:
              command: 'buildAndPush'
              dockerfile: 'Dockerfile'
              repository: $(ECR_REPOSITORY_URL)
              tags: '$(APP_VERSION)-$(Build.BuildNumber)'